# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#       # Set up Docker Buildx for various platforms 
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       # Log in to Docker Hub
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       # Extract Semantic Version Tag
#       - name: Extract Tag Version
#         id: version
#         run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

#       # Build and Push Docker Image
#       - name: Build and Push Docker Image
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: true
#           platforms: linux/amd64,linux/arm64
#           tags: |
#             ${{ secrets.DOCKERHUB_USERNAME }}/jomacs-devops:${{ env.VERSION }}
#             ${{ secrets.DOCKERHUB_USERNAME }}/jomacs-devops:latest

    

name: CI/CD Pipeline  # This is the name of the workflow

on:
  workflow_dispatch:  # This allows you to trigger the workflow manually
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'  # Default input if no input is provided
      version:
        description: 'Version to deploy'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the environment for the job
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the repository's code

      # Add other steps as needed for your workflow
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/myportfolio:${{ github.event.inputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/myportfolio:latest
