name: Deploy to Dokker and ECR 
on: 
  workflow_dispatch:
  push:
    tags:
      - 'v?[0-9]+\.[0-9]+'
       # Matches tags like 1.0.0, 2.1.3, etc.

jobs:
  build-and-push-to-Docker-Repo:
    runs-on: ubuntu-latest
    environment: DOCKER_ENV

    steps:
      # Step 1: Checkout the repository (this ensures the latest code is available)
      - name: Checkout code
        uses: actions/checkout@v3  

      # Step 2: Set up Docker Buildx so docker can build images for diffrent plafform 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Extract Tag Version
      - name: Extract Tag Version
        id: version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Step 5: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
  # Push_to_ERR:
  #   runs-on: ubuntu-latest
  #   environment: ECR_ENV
  #   steps:



