name: Deploy to Dokker and ECR 
on: 
  # workflow_dispatch:
  push:
    tags:
      - 'v?[0-9]+\.[0-9]+'
       # Matches tags like 1.0.0, 2.1.3, etc.

jobs:
  build-and-push-to-Docker-Repo:
    runs-on: ubuntu-latest
    environment: DOCKER_ENV

    steps:
      # Step 1: Checkout the repository (this ensures the latest code is available)
      - name: Checkout code
        uses: actions/checkout@v3  

      # Step 2: Set up Docker Buildx so docker can build images for diffrent plafform 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Extract Tag Version
      - name: Extract Tag Version
        id: version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Step 5: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
  
  Push_to_ERR:
    runs-on: ubuntu-latest
    environment: ECR_ENV
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: resume_app 
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG




